<a href="https://colab.research.google.com/github/quangvinht/Phan_tich_du_lieu_hoc_sau/blob/main/Lab_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as numpy
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/quangvinht/Phan_tich_du_lieu_hoc_sau/main/dulieuxettuyendaihoc.csv')
print(df)

    STT   T1   L1   H1   S1   V1   X1  ...  GT  DT   KV   DH1   DH2   DH3  KT
0     1  7.2  7.3  6.3  7.3  7.0  7.9  ...   F NaN  2NT  3.25  3.25  4.50  A1
1     2  5.4  3.9  3.9  4.0  5.4  5.4  ...   M NaN    1  6.00  4.00  3.50   C
2     3  5.6  6.8  7.2  7.5  4.3  7.4  ...   M NaN    1  5.00  6.75  4.00   C
3     4  6.6  6.4  5.3  6.9  5.4  7.3  ...   M NaN    1  4.25  4.25  5.25  D1
4     5  6.0  5.0  6.0  7.3  6.5  7.7  ...   M NaN  2NT  4.25  4.50  5.00   A
..  ...  ...  ...  ...  ...  ...  ...  ...  ..  ..  ...   ...   ...   ...  ..
95   96  8.6  6.9  7.4  8.8  7.6  5.8  ...   F NaN    1  5.25  1.50  6.25   C
96   97  3.7  5.4  6.0  5.1  5.5  3.9  ...   F NaN    1  5.25  3.75  4.75   C
97   98  8.8  5.5  7.4  7.7  6.2  7.3  ...   M NaN  2NT  7.00  8.00  4.00   C
98   99  2.7  1.8  3.4  5.3  4.5  7.9  ...   M NaN    1  5.00  3.50  5.50   C
99  100  4.1  5.2  4.9  5.3  5.5  5.4  ...   M NaN  2NT  5.25  2.50  4.25   C

[100 rows x 56 columns]

In [ ]:
 print("in ra 10 dòng đầu:") 
 print(df.head(10))

in ra 10 dòng đầu:
   STT   T1   L1   H1   S1   V1   X1  ...  GT  DT   KV   DH1   DH2   DH3  KT
0    1  7.2  7.3  6.3  7.3  7.0  7.9  ...   F NaN  2NT  3.25  3.25  4.50  A1
1    2  5.4  3.9  3.9  4.0  5.4  5.4  ...   M NaN    1  6.00  4.00  3.50   C
2    3  5.6  6.8  7.2  7.5  4.3  7.4  ...   M NaN    1  5.00  6.75  4.00   C
3    4  6.6  6.4  5.3  6.9  5.4  7.3  ...   M NaN    1  4.25  4.25  5.25  D1
4    5  6.0  5.0  6.0  7.3  6.5  7.7  ...   M NaN  2NT  4.25  4.50  5.00   A
5    6  9.3  7.6  7.9  8.6  7.0  7.3  ...   M NaN    1  1.50  4.00  6.00  D1
6    7  2.8  3.9  5.5  6.9  5.0  7.3  ...   F NaN    2  6.50  6.75  5.25   C
7    8  8.3  6.0  7.6  5.1  7.5  4.7  ...   F NaN    2  3.75  4.50  4.25  D1
8    9  6.5  6.3  7.6  6.0  5.5  7.1  ...   F NaN    1  3.50  3.50  6.75  D1
9   10  7.3  5.9  4.7  7.1  6.7  7.9  ...   F NaN    1  4.00  4.75  5.50  D1

[10 rows x 56 columns]

In [ ]:
print("in ra 10 dòng cuối:") 
print(df.tail(10))

in ra 10 dòng cuối:
    STT   T1   L1   H1   S1   V1   X1  ...  GT  DT   KV   DH1   DH2   DH3  KT
90   91  8.1  7.7  9.1  8.5  6.1  8.6  ...   M NaN    2  6.25  4.00  6.50   A
91   92  7.8  6.5  6.7  5.4  6.2  4.8  ...   M NaN  2NT  4.75  4.75  4.50   A
92   93  5.0  6.6  6.5  7.2  5.8  6.7  ...   M NaN    1  3.25  5.25  4.25   A
93   94  5.2  5.2  6.8  7.9  6.6  8.9  ...   M NaN    1  3.50  4.25  5.00   A
94   95  5.8  5.9  7.6  6.1  5.3  8.1  ...   M NaN    1  4.25  2.50  4.75   A
95   96  8.6  6.9  7.4  8.8  7.6  5.8  ...   F NaN    1  5.25  1.50  6.25   C
96   97  3.7  5.4  6.0  5.1  5.5  3.9  ...   F NaN    1  5.25  3.75  4.75   C
97   98  8.8  5.5  7.4  7.7  6.2  7.3  ...   M NaN  2NT  7.00  8.00  4.00   C
98   99  2.7  1.8  3.4  5.3  4.5  7.9  ...   M NaN    1  5.00  3.50  5.50   C
99  100  4.1  5.2  4.9  5.3  5.5  5.4  ...   M NaN  2NT  5.25  2.50  4.25   C

[10 rows x 56 columns]

In [ ]:
#Câu 4:
df['DT'].fillna( 0 , inplace= True )
#Câu 5: 
df['T1'].fillna( df['T1'].mean() , inplace= True )
print(df)

    STT   T1   L1   H1   S1   V1   X1  ...  GT   DT   KV   DH1   DH2   DH3  KT
0     1  7.2  7.3  6.3  7.3  7.0  7.9  ...   F  0.0  2NT  3.25  3.25  4.50  A1
1     2  5.4  3.9  3.9  4.0  5.4  5.4  ...   M  0.0    1  6.00  4.00  3.50   C
2     3  5.6  6.8  7.2  7.5  4.3  7.4  ...   M  0.0    1  5.00  6.75  4.00   C
3     4  6.6  6.4  5.3  6.9  5.4  7.3  ...   M  0.0    1  4.25  4.25  5.25  D1
4     5  6.0  5.0  6.0  7.3  6.5  7.7  ...   M  0.0  2NT  4.25  4.50  5.00   A
..  ...  ...  ...  ...  ...  ...  ...  ...  ..  ...  ...   ...   ...   ...  ..
95   96  8.6  6.9  7.4  8.8  7.6  5.8  ...   F  0.0    1  5.25  1.50  6.25   C
96   97  3.7  5.4  6.0  5.1  5.5  3.9  ...   F  0.0    1  5.25  3.75  4.75   C
97   98  8.8  5.5  7.4  7.7  6.2  7.3  ...   M  0.0  2NT  7.00  8.00  4.00   C
98   99  2.7  1.8  3.4  5.3  4.5  7.9  ...   M  0.0    1  5.00  3.50  5.50   C
99  100  4.1  5.2  4.9  5.3  5.5  5.4  ...   M  0.0  2NT  5.25  2.50  4.25   C

[100 rows x 56 columns]

In [ ]:
#cau 6:

def fill(col):
  return df[col].fillna( df[col].mean() , inplace= True  )

isfloat64=df.dtypes == float
df_column_list = df.columns[isfloat64]

for col in df_column_list:
  fill(col)

print(df.head(10))

   STT   T1   L1   H1   S1   V1   X1  ...  GT   DT   KV   DH1   DH2   DH3  KT
0    1  7.2  7.3  6.3  7.3  7.0  7.9  ...   F  0.0  2NT  3.25  3.25  4.50  A1
1    2  5.4  3.9  3.9  4.0  5.4  5.4  ...   M  0.0    1  6.00  4.00  3.50   C
2    3  5.6  6.8  7.2  7.5  4.3  7.4  ...   M  0.0    1  5.00  6.75  4.00   C
3    4  6.6  6.4  5.3  6.9  5.4  7.3  ...   M  0.0    1  4.25  4.25  5.25  D1
4    5  6.0  5.0  6.0  7.3  6.5  7.7  ...   M  0.0  2NT  4.25  4.50  5.00   A
5    6  9.3  7.6  7.9  8.6  7.0  7.3  ...   M  0.0    1  1.50  4.00  6.00  D1
6    7  2.8  3.9  5.5  6.9  5.0  7.3  ...   F  0.0    2  6.50  6.75  5.25   C
7    8  8.3  6.0  7.6  5.1  7.5  4.7  ...   F  0.0    2  3.75  4.50  4.25  D1
8    9  6.5  6.3  7.6  6.0  5.5  7.1  ...   F  0.0    1  3.50  3.50  6.75  D1
9   10  7.3  5.9  4.7  7.1  6.7  7.9  ...   F  0.0    1  4.00  4.75  5.50  D1

[10 rows x 56 columns]

In [ ]:
#câu 7:
for i in ['1','2','6']:
  df['TBM'+i] = (df['T'+i]*2 + df['L'+i]+ df['H'+i]+ df['S'+i]+ df['V'+i]*2 + df['X'+i]+ df['D'+i]+ df['N'+i]) / 10

df.rename(columns={'TBM6':'TBM3'})

    STT   T1   L1   H1   S1   V1   X1  ...   DH1   DH2   DH3  KT  TBM1  TBM2  TBM3
0     1  7.2  7.3  6.3  7.3  7.0  7.9  ...  3.25  3.25  4.50  A1  7.00  7.54  7.01
1     2  5.4  3.9  3.9  4.0  5.4  5.4  ...  6.00  4.00  3.50   C  4.69  5.47  5.07
2     3  5.6  6.8  7.2  7.5  4.3  7.4  ...  5.00  6.75  4.00   C  5.77  5.38  6.04
3     4  6.6  6.4  5.3  6.9  5.4  7.3  ...  4.25  4.25  5.25  D1  6.21  5.20  6.88
4     5  6.0  5.0  6.0  7.3  6.5  7.7  ...  4.25  4.50  5.00   A  6.50  6.36  6.99
..  ...  ...  ...  ...  ...  ...  ...  ...   ...   ...   ...  ..   ...   ...   ...
95   96  8.6  6.9  7.4  8.8  7.6  5.8  ...  5.25  1.50  6.25   C  7.43  7.42  6.83
96   97  3.7  5.4  6.0  5.1  5.5  3.9  ...  5.25  3.75  4.75   C  4.93  5.15  6.39
97   98  8.8  5.5  7.4  7.7  6.2  7.3  ...  7.00  8.00  4.00   C  7.05  7.84  7.67
98   99  2.7  1.8  3.4  5.3  4.5  7.9  ...  5.00  3.50  5.50   C  4.15  4.72  5.29
99  100  4.1  5.2  4.9  5.3  5.5  5.4  ...  5.25  2.50  4.25   C  5.26  5.72  5.85

[100 rows x 59 columns]

In [ ]:
# for i in ['1','2','3']:
  # if (df['TBM'+i] < 5):
  #     df['XL'+i] = 'Y'
  # if df['TBM'+i] >= 5 and df['TBM'+i] < 6.5:
  #     df['XL'+i] = 'TB'
  # if df['TBM'+i] >= 6.5 and df['TBM'+i] < 8: 
  #     df['XL'+i] = 'K'
  # if df['TBM'+i] >= 8 and df['TBM'+i] < 9: 
  #     df['XL'+i] = 'G'
  # if df['TBM'+i] > 9: 
  #     df['XL'+i] = 'XS'

#câu 8:
df.loc[ (df['TBM1']  < 5) , 'XL1' ] = 'Y'
df.loc[ (df['TBM1'] >= 5) & (df['TBM1'] < 6.5) , 'XL1'] = 'TB'
df.loc[ (df['TBM1'] >= 6.5) & (df['TBM1'] < 8) , 'XL1'] = 'K'
df.loc[ (df['TBM1'] >= 8) & (df['TBM1'] < 9) , 'XL1'] = 'G'
df.loc[(df['TBM1']  > 9) , 'XL1'] = 'XS'

df.loc[ (df['TBM2']  < 5) , 'XL2' ] = 'Y'
df.loc[ (df['TBM2'] >= 5) & (df['TBM2'] < 6.5) , 'XL2'] = 'TB'
df.loc[ (df['TBM2'] >= 6.5) & (df['TBM2'] < 8) , 'XL2'] = 'K'
df.loc[ (df['TBM2'] >= 8) & (df['TBM2'] < 9) , 'XL2'] = 'G'
df.loc[(df['TBM2']  > 9) , 'XL2'] = 'XS'


df.loc[ (df['TBM6']  < 5) , 'XL3' ] = 'Y'
df.loc[ (df['TBM6'] >= 5) & (df['TBM6'] < 6.5) , 'XL3'] = 'TB'
df.loc[ (df['TBM6'] >= 6.5) & (df['TBM6'] < 8) , 'XL3'] = 'K'
df.loc[ (df['TBM6'] >= 8) & (df['TBM6'] < 9) , 'XL3'] = 'G'
df.loc[(df['TBM6']  > 9) , 'XL3'] = 'XS'

print(df)

    STT   T1   L1   H1   S1   V1   X1  ...  KT  TBM1  TBM2  TBM6  XL1  XL2  XL3
0     1  7.2  7.3  6.3  7.3  7.0  7.9  ...  A1  7.00  7.54  7.01    K    K    K
1     2  5.4  3.9  3.9  4.0  5.4  5.4  ...   C  4.69  5.47  5.07    Y   TB   TB
2     3  5.6  6.8  7.2  7.5  4.3  7.4  ...   C  5.77  5.38  6.04   TB   TB   TB
3     4  6.6  6.4  5.3  6.9  5.4  7.3  ...  D1  6.21  5.20  6.88   TB   TB    K
4     5  6.0  5.0  6.0  7.3  6.5  7.7  ...   A  6.50  6.36  6.99    K   TB    K
..  ...  ...  ...  ...  ...  ...  ...  ...  ..   ...   ...   ...  ...  ...  ...
95   96  8.6  6.9  7.4  8.8  7.6  5.8  ...   C  7.43  7.42  6.83    K    K    K
96   97  3.7  5.4  6.0  5.1  5.5  3.9  ...   C  4.93  5.15  6.39    Y   TB   TB
97   98  8.8  5.5  7.4  7.7  6.2  7.3  ...   C  7.05  7.84  7.67    K    K    K
98   99  2.7  1.8  3.4  5.3  4.5  7.9  ...   C  4.15  4.72  5.29    Y    Y   TB
99  100  4.1  5.2  4.9  5.3  5.5  5.4  ...   C  5.26  5.72  5.85   TB   TB   TB

[100 rows x 62 columns]

In [ ]:
#câu 9 :
for i in ['1','2','6']:
  df['US_TMB'+i] = (df['TBM'+i]/10) * 4
print(df['US_TMB1'])

0     2.800
1     1.876
2     2.308
3     2.484
4     2.600
      ...
95    2.972
96    1.972
97    2.820
98    1.660
99    2.104
Name: US_TMB1, Length: 100, dtype: float64

In [ ]:
#CÂU 10 :
df.loc[ ( ( (df['DH1']*2 +df['DH2'] +df['DH2'])/4 ) >=5) & ( (df['KT'] =='A') |  (df['KT'] =='A1')   ) , 'KQXT'] = '1 '
df.loc[ ( ( (df['DH1']*2 +df['DH2'] +df['DH2'])/4 ) <5) & ( (df['KT'] =='A') |  (df['KT'] =='A1')   ) , 'KQXT'] = '0 '


df.loc[ ( ( (df['DH1'] +df['DH2']*2 +df['DH2'])/4 ) >=5) &  (df['KT'] =='B')   , 'KQXT'] = '1 '
df.loc[ ( ( (df['DH1'] +df['DH2']*2 +df['DH2'])/4 ) <5) &  (df['KT'] =='B')    , 'KQXT'] = '0 '


df.loc[ ( ( (df['DH1'] +df['DH2'] +df['DH2'])/4 ) >=5) & ( (df['KT'] !='A') &  (df['KT'] =='A1') & (df['KT'] =='B') ) , 'KQXT'] = '1 '
df.loc[ ( ( (df['DH1'] +df['DH2'] +df['DH2'])/4 ) <5) & ( (df['KT'] !='A') &  (df['KT'] =='A1') & (df['KT'] =='B') ) , 'KQXT'] = '0 '


print(df)

#CÂU 11:
df.to_csv('processed_dulieuxettuyendaihoc.csv')

    STT   T1   L1   H1   S1   V1  ...  XL2  XL3  US_TMB1  US_TMB2  US_TMB6  KQXT
0     1  7.2  7.3  6.3  7.3  7.0  ...    K    K    2.800    3.016    2.804    0
1     2  5.4  3.9  3.9  4.0  5.4  ...   TB   TB    1.876    2.188    2.028   NaN
2     3  5.6  6.8  7.2  7.5  4.3  ...   TB   TB    2.308    2.152    2.416   NaN
3     4  6.6  6.4  5.3  6.9  5.4  ...   TB    K    2.484    2.080    2.752   NaN
4     5  6.0  5.0  6.0  7.3  6.5  ...   TB    K    2.600    2.544    2.796    0
..  ...  ...  ...  ...  ...  ...  ...  ...  ...      ...      ...      ...   ...
95   96  8.6  6.9  7.4  8.8  7.6  ...    K    K    2.972    2.968    2.732   NaN
96   97  3.7  5.4  6.0  5.1  5.5  ...   TB   TB    1.972    2.060    2.556   NaN
97   98  8.8  5.5  7.4  7.7  6.2  ...    K    K    2.820    3.136    3.068   NaN
98   99  2.7  1.8  3.4  5.3  4.5  ...    Y   TB    1.660    1.888    2.116   NaN
99  100  4.1  5.2  4.9  5.3  5.5  ...   TB   TB    2.104    2.288    2.340   NaN

[100 rows x 66 columns]